[('Hopital Cavale', 1),
  ('Hopital Cavale 2', 1),
  ('Hopital Cavale 1', 1),
  ('Ecole Commerce', 1),
  ('Gascogne', 1),
  ('Dauphine', 1),
  ('Tarente', 1),
  ('Patinoire', 1),
  ('Kermenguy', 1),
  ('Bouguen', 1),
  ('Universites', 1),
  ('Albert 1er', 1),
  ('Malakoff', 1),
  ('Hotel de Ville', 1),
  ('Liberte Place', 1),
  ('Liberte Quartz', 1),
  ('Kennedy Gare', 1),
  ('Gare', 1),
  ('Kennedy Gare', 1),
  ('Rampes', 1),
  ('Musee Marine', 1),
  ('Francais Libres', 1),
  ('Recouvrance', 1),
  ('Maissin', 1),
  ('Javouhey', 1),
  ('Loti', 1),
  ("Fr. d' Esperey", 1),
  ('Kerangoff', 1),
  ('Paul Bert', 1),
  ('Kerbonne', 1),
  ('Cosmao Pretot', 1),
  ('Castel-an-Daol', 1),
  ('Bourayne', 1),
  ('Kerzudal', 1),
  ('St Pierre', 1),
  ('Panier Fleuri', 1),
  ('Fort Montbarey', 1)]
