 [('Liberte Morvan', 10),
  ('Multiplexe', 10),
  ('Hopital Morvan', 10),
  ('Foch', 10),
  ('Universites', 10),
  ('Bouguen', 10),
  ('Kermenguy', 10),
  ('Le Gorgeu', 10),
  ('Bergot', 10),
  ('Etang', 10),
  ('Gouez', 10),
  ('Penfeld', 10),
  ('Castelmein', 10),
  ('Coat ty Ogant', 10),
  ('Coat Mez', 10),
  ('Lancelot', 10),
  ('Guilers Mairie', 10),
  ('Kerionoc', 10),
  ('Kermengleuz', 10),
  ('Guilers Eglise', 10),
  ('Daurat', 10),
  ('Croas-ar-Pennoc', 10),
  ('Kerouriat', 10),
  ('La Source', 10),
  ('Roudous', 10),
  ('Kerzespez', 10),
  ('Chataigniers', 10),
  ('Manet', 10),
  ('Camelias', 10),
  ('Poull-Pren', 10),
  ('Freyssinet', 10),
  ('Roberval', 10)]
