[('Kerjean', 11),
  ('Keriguel', 11),
  ('Jezequel', 11),
  ('Mediatheque', 11),
  ('Cormorans', 11),
  ('Resistance', 11),
  ('Pont SNCF', 11),
  ('Kerhuon Mairie', 11),
  ('Guehenno', 11),
  ("Reun-ar-C'hoat", 11),
  ('Keroumen', 11),
  ('Fleming', 11),
  ('Le Reun', 11),
  ('Kerhuon Bourg', 11),
  ('Danton', 11),
  ('Kerscao', 11),
  ('Kerhuel', 11),
  ('Kermadec', 11),
  ('Ste Barbe', 11),
  ('Moulin Blanc', 11),
  ('Rody', 11),
  ('Palaren', 11),
  ('Jardin Botanique', 11),
  ('Rte de Quimper', 11),
  ('Floch', 11),
  ('Le Bot Haut', 11),
  ('Stade F.Le Ble', 11),
  ('Strasbourg', 11),
  ('Place Strasbourg', 11),
  ('Place Strasbourg', 11)]
