[("Pen-ar-c'hleuz", 12),
  ("Pen-ar-C'hleuz", 12),
  ('Kermaria', 12),
  ('Paulet', 12),
  ('8 mai 1945', 12),
  ('Kerzu', 12),
  ('Choiseul', 12),
  ('Kerichen Lesven', 12),
  ('Hoche', 12),
  ('Braille', 12),
  ('Strasbourg loupp', 12),
  ('Strasbourg', 12),
  ("Pen-ar-Creac'h", 12),
  ('Coq Hardi', 12),
  ('Kerbernard', 12),
  ('Pont Neuf', 12),
  ('Stang-Alar', 12),
  ('Tourbian', 12),
  ('Kervillerm', 12),
  ('Coataudon', 12),
  ('Froutven', 12),
  ('Salanguis', 12),
  ('Lavallot', 12),
  ('Ti-Ruz', 12),
  ('Coat-Jestin', 12),
  ('Kerjaouen', 12),
  ('Le Coat', 12),
  ('St-Herbot', 12),
  ('St-Eloi', 12),
  ('Pen-an-Dalar', 12),
  ('Kergompez', 12),
  ('Champagne', 12),
  ('Kerafur', 12),
  ('Ribeuze', 12),
  ('Pompidou', 12),
  ('Guipavas Awena', 12),
  ('Monnet', 12),
  ('Anne de Bretagne', 12),
  ('Keranna', 12)]
