[('Plouzane Mairie', 13),
  ('Mescouezel', 13),
  ('Kerrarouz', 13),
  ('Commerce', 13),
  ('Enclos', 13),
  ('Kerhourlo', 13),
  ('Croas ar Go', 13),
  ('Faraday', 13),
  ('Technopole', 13),
  ('Ecoles', 13),
  ('De Rochon', 13),
  ('Piccard', 13),
  ('Plage Ste Anne', 13),
  ('Cosquer', 13),
  ('Mimosas', 13),
  ('Portzic', 13),
  ("Chateau d'eau", 13),
  ('Porte Plouzane', 13),
  ('Fort Montbarey', 13)]
