[('Danton', 14),
  ('Danton', 14),
  ('Kerhuon Bourg', 14),
  ('Kerhuon Mairie', 14),
  ('Pont SNCF', 14),
  ('Resistance', 14),
  ('Cormorans', 14),
  ('Pyrotechnie', 14),
  ('Le Passage', 14),
  ('Camfrout', 14),
  ('Prince Russe', 14),
  ('Maze', 14),
  ('Le Mendy', 14),
  ('Baradozic', 14),
  ('Moulin Blanc', 14),
  ('Rody', 14),
  ('Palaren', 14),
  ('Jardin Botanique', 14),
  ('Rte de Quimper', 14),
  ('Floch', 14),
  ('Le Bot Haut', 14),
  ('Stade F.Le Ble', 14),
  ('Strasbourg', 14),
  ('Place Strasbourg', 14),
  ('Place Strasbourg', 14)]
