[('Plouzane Bourg', 15),
  ('Mouettes', 15),
  ("Lourc'h", 15),
  ('Landrean', 15),
  ('Cloitre', 15),
  ('Aber-Ildut', 15),
  ('Penhuel', 15),
  ('Malmanche', 15),
  ('Plouzane Mairie', 15),
  ('Kerallan', 15),
  ('Sycomores', 15),
  ('Bleuets', 15),
  ('Myosotis', 15),
  ('Commerce', 15),
  ('Enclos', 15),
  ('La Trinite', 15),
  ('Keramaze', 15),
  ('Lannevel-Braz', 15),
  ('Coatuelen', 15),
  ("Chateau d'eau", 15),
  ('Porte Plouzane', 15),
  ('Fort Montbarey', 15)]
