 [('Lantel', 16),
  ('Le Crann', 16),
  ('Frenes', 16),
  ('Guepratte', 16),
  ('Anjou', 16),
  ('Peupliers', 16),
  ('Capucines', 16),
  ('Le Bois', 16),
  ('Le Bras', 16),
  ('Place des Fusill', 16),
  ('De Gaulle', 16),
  ('Kerlois', 16),
  ('Kerinaouen', 16),
  ('Porte Gouesnou', 16)]
