 [('Prat Ledan', 17),
  ('A.France', 17),
  ('Le Moigne', 17),
  ('4 Moulins', 17),
  ('Kerbonne', 17),
  ('Kerbonne Eglise', 17),
  ('Dupetit Thouars', 17),
  ('Amundsen', 17),
  ('Mesdoun', 17),
  ('Keranquere', 17),
  ('Pouleder', 17),
  ('Stendhal', 17),
  ('Kerargaouyat', 17),
  ('Ypres', 17),
  ('Ecole Navale', 17),
  ('Ecole Navale', 17),
  ('Mesdoun', 17),
  ('Amundsen', 17),
  ('Dupetit Thouars', 17),
  ('Kerbonne Eglise', 17),
  ('Kerbonne', 17),
  ('4 Moulins', 17),
  ('Le Moigne', 17),
  ('A.France', 17),
  ('Prat Ledan', 17)]
