('Lambezellec', 3),
  ('Giloux', 3),
  ('Chapalain', 3),
  ('Place des FFI', 3),
  ('Place Bretagne', 3),
  ('Berlioz', 3),
  ('Couperin', 3),
  ('Treornou', 3),
  ('Gretry', 3),
  ('Gay Lussac', 3),
  ('Keralloche', 3),
  ('Kerinou', 3),
  ('Peguy', 3),
  ('Pasteur', 3),
  ('Albert 1er', 3),
  ('Malakoff', 3),
  ('Hotel de Ville', 3),
  ('Liberte Place', 3),
  ('Liberte Quartz', 3),
  ('Gambetta-Gare', 3),
  ('Republique', 3),
  ('Sane', 3),
  ('Sanquer', 3),
  ('Richelieu', 3),
  ('Octroi', 3),
  ('Poul-ar-Bachet', 3),
  ('Douric', 3),
  ('Rodin', 3),
  ('Guynemer', 3),
  ("D'Estrees", 3),
  ('Maleyssie', 3),
  ('Brazza', 3),
  ('Dixmude', 3),
  ('St Marc', 3),
  ('Kerisbian', 3),
  ('Bernard', 3),
  ('Le Goffic', 3),
  ('Landelle', 3),
  ('Palaren', 3),
  ('Port Plaisance', 3),
  ('Ty-Yann', 3),
  ('Oceanopolis', 3)]
