[('Hopital Cavale 2', 4),
  ('Questel', 4),
  ('Prigent', 4),
  ('Le Greco', 4),
  ("Amiral Ronarc'h", 4),
  ('Kant', 4),
  ('Michel-Ange', 4),
  ('Schubert', 4),
  ('Warspite', 4),
  ('Tallinn', 4),
  ('Kerfeunteun', 4),
  ('Vali Hir', 4),
  ('Polygone', 4),
  ('Beaumanoir', 4),
  ('Route de Guilers', 4),
  ('Landais', 4),
  ('Les Capucins', 4),
  ('Coppin', 4),
  ('Harteloire', 4),
  ('Multiplexe', 4),
  ('Liberte Quartz', 4),
  ('Kennedy Gare', 4),
  ('Rampes', 4),
  ('Port du Chateau', 4),
  ('Les iles', 4),
  ('La Carene', 4),
  ('Port de Commerce', 4),
  ('Formes', 4)]
