[('Provence', 5),
  ('Porte Gouesnou', 5),
  ('Porte Gouesnou', 5),
  ('Lagadec', 5),
  ('Keruchen', 5),
  ('Keraudren', 5),
  ('Niepce', 5),
  ('Poul ar Feunteun', 5),
  ('Baudot', 5),
  ('Broussais', 5),
  ('Dunant', 5),
  ('Lanroze', 5),
  ('St Vincent', 5),
  ('Lambezellec', 5),
  ('Giloux', 5),
  ('Chapalain', 5),
  ('Place des FFI', 5),
  ('Place Bretagne', 5),
  ('Pen-ar-Menez', 5),
  ('Croix Rouge', 5),
  ('Jules Lesven', 5),
  ('Kerichen Lesven', 5),
  ('4 Chemins', 5),
  ('Choiseul', 5),
  ('Dourjacq', 5),
  ('Villeneuve', 5),
  ('Coulomb', 5),
  ('Kergonan', 5),
  ('Pont Neuf', 5),
  ('Kerbernard', 5),
  ('Coq Hardi', 5),
  ("Pen-ar-Creac'h", 5),
  ('Strasbourg', 5),
  ('Strasbourg Valmy', 5),
  ('Lyautey', 5),
  ('Rodin', 5),
  ('Guynemer', 5),
  ('Guelmeur Eglise', 5),
  ("D'Est. d'Orves", 5),
  ('Forestou', 5),
  ('Sane', 5),
  ('Republique', 5),
  ('Gambetta-Gare', 5),
  ('Liberte Quartz', 5),
  ('Multiplexe', 5),
  ('C A F', 5),
  ('Portzmoguer', 5),
  ('Boulogne', 5),
  ('Segur', 5),
  ('Bouguen', 5),
  ('Kermenguy', 5),
  ("Duc d'Aumale", 5),
  ('Kergoat', 5),
  ('Garnier', 5),
  ('Clauzel', 5),
  ('Normandie', 5),
  ('Patinoire', 5),
  ('Vendee', 5),
  ('Saintonge', 5),
  ('Berry', 5),
  ('Dauphine', 5),
  ('Gascogne', 5),
  ('Provence', 5)]
