[('Cl.Keraudren', 6),
  ('Keraudren', 6),
  ("Maison d'arret", 6),
  ('Kermaria', 6),
  ("Pen-ar-C'hleuz", 6),
  ('Le Nobletz', 6),
  ('Giloux', 6),
  ('Chapalain', 6),
  ('Place des FFI', 6),
  ('Place Bretagne', 6),
  ('Berlioz', 6),
  ('AFPA', 6),
  ('Chatellier', 6),
  ('Charpentier', 6),
  ('Franklin', 6),
  ('Gay Lussac', 6),
  ('ISEN', 6),
  ('Cuirasse', 6),
  ('Langevin', 6),
  ('Kermenguy', 6),
  ('Kerhallet', 6),
  ('Anse Saupin', 6),
  ('La Digue', 6),
  ('Liberation', 6),
  ('Kant', 6),
  ("Amiral Ronarc'h", 6),
  ('Le Greco', 6),
  ('Wagner', 6),
  ('Demy', 6),
  ('Feuillere', 6),
  ('Mesnos', 6),
  ('Lanninguer', 6),
  ('Coat Tan', 6),
  ('Emile Rousse', 6),
  ('Tartu', 6),
  ('Bourayne', 6),
  ('Mesdoun', 6),
  ('Ecole Navale', 6),
  ('Ypres', 6),
  ('Kerargaouyat', 6),
  ('Stendhal', 6),
  ('Pouleder', 6),
  ('Quilbignon', 6),
  ('Comte', 6),
  ('Taine', 6),
  ('Kernabat', 6),
  ('De Nerval', 6),
  ('Casabianca', 6),
  ('Cruguel', 6),
  ('Cocteau', 6),
  ('Thibaudet', 6),
  ('Gergotich', 6),
  ('Fort Montbarey', 6),
  ('Fort Montbarey', 6)]
