[('Petite Gare', 7),
  ('Petite Gare', 7),
  ('Fortin', 7),
  ('Rte de Bohars', 7),
  ('Hopital Tromeur', 7),
  ('Clinique Iroise', 7),
  ('Petit Kerven', 7),
  ('Marregues', 7),
  ('Grand Kerizac', 7),
  ('Du Prajen', 7),
  ('Messioual', 7),
  ('Messioual', 7),
  ('Kervao', 7),
  ('Loscoat', 7),
  ('Kercastrec', 7),
  ('Rostand', 7),
  ('Brasserie', 7),
  ('Place des FFI', 7),
  ('Chapalain', 7),
  ('St Christophe', 7),
  ('Mirabeau', 7),
  ('Blum', 7),
  ('Kerichen Lycee', 7),
  ('St Luc', 7),
  ('Messidou', 7),
  ('Kerigonan', 7),
  ('Malakoff', 7),
  ('Hotel de Ville', 7),
  ('Liberte Frezier', 7)]
