[('Ty ar Menez', 8),
  ('Colas', 8),
  ('Kervenal', 8),
  ('Croas-ar-Bis', 8),
  ('Guivarch', 8),
  ('Kerdangui', 8),
  ('Champ de Foire', 8),
  ('Meheut', 8),
  ('Fontaine Blanche', 8),
  ('Kerbrat', 8),
  ('Toull-ar-Ranig', 8),
  ('Bodonn', 8),
  ('Salaun', 8),
  ('Filliger', 8),
  ('Deredec', 8),
  ("Roc'h-Kerezen", 8),
  ('Ty Armor', 8),
  ('Kap Huella', 8),
  ('Rody', 8),
  ('Palaren', 8),
  ('Jardin Botanique', 8),
  ('Rte de Quimper', 8),
  ('Floch', 8),
  ('Le Bot Haut', 8),
  ('Stade F.Le Ble', 8),
  ('Strasbourg', 8),
  ('Strasbourg', 8),
  ('Braille', 8),
  ('Hoche', 8),
  ('Montaigne', 8),
  ('Le Moult', 8),
  ('Donnart', 8),
  ('Albert 1er', 8),
  ('Malakoff', 8),
  ('Hotel de Ville', 8),
  ('Liberte Frezier', 8)]
