[('Petite Gare', 9),
  ('Pen-ar-Guear', 9),
  ('Bohars Bourg', 9),
  ('Chapelle', 9),
  ('Beuzit', 9),
  ('Bohars-Kerguillo', 9),
  ('Seguin', 9),
  ('Roz-Vian', 9),
  ('Lannoc', 9),
  ('Etang', 9),
  ('Bourbonnais', 9),
  ('Tarente', 9),
  ('Patinoire', 9),
  ('Kermenguy', 9),
  ('Bouguen', 9),
  ('Universites', 9),
  ('Foch', 9),
  ('Hopital Morvan', 9),
  ('Liberte Morvan', 9)]
